name: sp500-intel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - statsmodels
  - scikit-learn
  - plotly
  - pip
  - kaleido
  - pyarrow
  - tabulate
  - pip:
    - yfinance
    - prophet
    - streamlit
    - holidays
    - arch
    - pandas_market_calendars